"""empty message

Revision ID: 044103e0e498
Revises: 00d406ecf043
Create Date: 2018-11-06 23:09:48.307821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044103e0e498'
down_revision = '00d406ecf043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('RA', sa.Integer(), nullable=False),
    sa.Column('Ativo', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Alunos')
    # ### end Alembic commands ###
