"""empty message

Revision ID: 23179b7507ec
Revises: 
Create Date: 2019-03-28 18:39:32.348279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23179b7507ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clinte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('CPF', sa.String(length=80), nullable=False),
    sa.Column('telefone', sa.String(length=80), nullable=False),
    sa.Column('Endereco', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('CPF')
    )
    op.create_table('Fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User', sa.String(length=20), nullable=False),
    sa.Column('Senha', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Senha'),
    sa.UniqueConstraint('User')
    )
    op.create_table('Produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('preco', sa.Float(precision=120), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['Fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(precision=120), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('cliente_cpf', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_cpf'], ['Clinte.CPF'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['Produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['Orcamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pedido')
    op.drop_table('Orcamento')
    op.drop_table('Produtos')
    op.drop_table('Usuario')
    op.drop_table('Fornecedor')
    op.drop_table('Clinte')
    # ### end Alembic commands ###
