"""empty message

Revision ID: 4f4bac09f439
Revises: 
Create Date: 2019-06-07 00:37:12.724895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4bac09f439'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('CPF', sa.String(length=80), nullable=False),
    sa.Column('telefone', sa.String(length=80), nullable=False),
    sa.Column('Endereco', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('CPF')
    )
    op.create_table('Fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User', sa.String(length=20), nullable=False),
    sa.Column('Senha', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Senha'),
    sa.UniqueConstraint('User')
    )
    op.create_table('Orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(precision=120), nullable=False),
    sa.Column('cliente_cpf', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_cpf'], ['Cliente.CPF'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('preco', sa.Float(precision=120), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['Fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Orcamento_Produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('Produto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Produto_id'], ['Produtos.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['Orcamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['Orcamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pedido')
    op.drop_table('Orcamento_Produto')
    op.drop_table('Produtos')
    op.drop_table('Orcamento')
    op.drop_table('Usuario')
    op.drop_table('Fornecedor')
    op.drop_table('Cliente')
    # ### end Alembic commands ###
