"""empty message

Revision ID: 6e3c7d0f9594
Revises: 
Create Date: 2019-06-19 16:20:34.236652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3c7d0f9594'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CategoriaProduto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Categoria', sa.String(length=20), nullable=False),
    sa.Column('CalcularMetragem', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Categoria')
    )
    op.create_table('Cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('CPF', sa.String(length=80), nullable=False),
    sa.Column('telefone', sa.String(length=80), nullable=False),
    sa.Column('Endereco', sa.String(length=80), nullable=False),
    sa.Column('Cidade', sa.String(length=80), nullable=False),
    sa.Column('Estado', sa.String(length=80), nullable=False),
    sa.Column('Complemento', sa.String(length=80), nullable=True),
    sa.Column('CEP', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('CPF')
    )
    op.create_table('Fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(precision=120), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('prazoEntrega', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User', sa.String(length=20), nullable=False),
    sa.Column('Senha', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Senha'),
    sa.UniqueConstraint('User')
    )
    op.create_table('Pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('cliente_cpf', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_cpf'], ['Cliente.CPF'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['Orcamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('preco', sa.Float(precision=120), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_cnpj', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['CategoriaProduto.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_cnpj'], ['Fornecedor.cnpj'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Orcamento_Produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('Produto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Produto_id'], ['Produtos.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['Orcamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Orcamento_Produto')
    op.drop_table('Produtos')
    op.drop_table('Pedido')
    op.drop_table('Usuario')
    op.drop_table('Orcamento')
    op.drop_table('Fornecedor')
    op.drop_table('Cliente')
    op.drop_table('CategoriaProduto')
    # ### end Alembic commands ###
