"""empty message

Revision ID: 9ddd0c0b4189
Revises: e4332a630f14
Create Date: 2018-11-20 22:58:56.641810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddd0c0b4189'
down_revision = 'e4332a630f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User', sa.String(length=20), nullable=False),
    sa.Column('Senha', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Senha'),
    sa.UniqueConstraint('User')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Usuario')
    # ### end Alembic commands ###
