"""empty message

Revision ID: e4332a630f14
Revises: 
Create Date: 2018-11-20 11:55:47.311213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4332a630f14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('CPF', sa.String(length=80), nullable=False),
    sa.Column('telefone', sa.String(length=80), nullable=False),
    sa.Column('Endereco', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('CPF')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('preco', sa.Float(precision=120), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(precision=120), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('cliente_cpf', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_cpf'], ['clientes.CPF'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_table('orcamentos')
    op.drop_table('produtos')
    op.drop_table('fornecedores')
    op.drop_table('clientes')
    # ### end Alembic commands ###
