"""empty message

Revision ID: ffe67ea3c645
Revises: 4f4bac09f439
Create Date: 2019-06-07 00:43:24.318081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe67ea3c645'
down_revision = '4f4bac09f439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orcamento', sa.Column('data', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orcamento', 'data')
    # ### end Alembic commands ###
